### PR TITLE
FIX: using namespaces --> This parameter is not passed to the request

### PR DESCRIPTION
**Pull request by i4s-pserrano**
Using python-nomad 1.0.1 if you try to access Nomad with namespaces, you can't get the objects of specific namespace. This pull request solve it.

### CODE REVIEW

**Comment by jrxFive** [comment]
Hey @i4s-pserrano, thanks for the quick issue/fix. Do you have sample snippet of whats trying to be done from the client library; instantiation, request, returned output and possibly what the url should have been?

Mostly so I can add a test for this scenario to make sure we don't regress. Thanks!

**Comment by i4s-pserrano** [comment]
Hey @jrxFive. I great to help you! 

I'm trying to get the deployments over one namespace. The api returns and empty list becase the params doest have the parameter (namespace="admin"). This namespace was instanciated with variables

NOMAD_ADDR=https://my_system
NOMAD_NAMESPACE=admin
NOMAD_TOKEN=xxxx-xxxx-xxxx-xxxx
NOMAD_REGION=eu

If I have time this evening, I will add a test.

regards

**Comment by i4s-pserrano** [comment]
Hi @jrxFive . I added some test. Please review if you are confortable with this changes. At my last commit, I have resolved the conflict with test_job.py

Regards

**Comment by jrxFive** [comment]
@i4s-pserrano, still looks like there is a conflict with `test_job.py` also is there a reason why you deleted `example_batch_parameterized.json`?

**Comment by i4s-pserrano** [comment]
It was my fault...  recovered you job test file

**Pull request merged**
