### PR TITLE
add support for namespace argument in get_job

### LINKED ISSUE #118: Add support for namespace in get_job
Similiary to https://github.com/jrxFive/python-nomad/pull/115, I'd like support for passing the namespace to the get_job function. The API already supports it: https://www.nomadproject.io/api-docs/jobs#read-job

This way I can connect to the nomad-API with a specific namespace but can also get jobs from other namespaces.

### PR DESCRIPTION
**Pull request by rndmh3ro**
fixes #118

### CODE REVIEW

**Comment by jonathanrcross** [comment]
Hi @rndmh3ro, thanks for the PR! I took a look at this and at first glance -- I thought it would work-- but further inspected base.py:

https://github.com/jrxFive/python-nomad/blob/0d462bd05d12a7c9ad310d5b66cd4897e58a41b0/nomad/api/base.py#L64-L73

which is called by base.py._request as a pre-step before issuing the actual http call:
https://github.com/jrxFive/python-nomad/blob/0d462bd05d12a7c9ad310d5b66cd4897e58a41b0/nomad/api/base.py#L89-L96

The issue is that if when instantiating a `nomad.Nomad` object if the namespace parameter was given, this will currently always override whatever you pass as the namespace parameter via method. We can change `_query_string_builder` to have a parameter for the `params` and check if `namespace` or `region` are already declared and avoid overriding them.

Additionally we should add a couple tests to `get_job` to verify we are indeed requesting the namespace we think we are! I can certainly help out with the changes if needed. A current workaround if this is blocking you is to create different `nomad.Nomad` objects with the namespace as part of the constructor you want to target.

**Comment by jrxFive** [comment]
hi @rndmh3ro, I worked #120 this should allow us to merge your PR! Ideally if you do have time it be great if you could add a test to verify from the get_jobs level --probably using a mock/responses -- to verify that the querystring is indeed what is being passed. If not we can merge and ill add a test in a follow up. Thanks again!

**Comment by jrxFive** [comment]
Hi @rndmh3ro I added/merged #120 and #121 based on your PR! Thank you for the your contribution.

**Comment by rndmh3ro** [comment]
Thank you for doing this!

**Pull request closed without merging**
