### PR TITLE
update parameters in `Job` functions

### PR DESCRIPTION
**Pull request by IgnacioHeredia**
Just a little update on the parameters in `deregister_job()`. Tested it.

I choose `Union` instead of `Optional` for parameters [in line with this](https://fastapi.tiangolo.com/python-types/#using-union-or-optional).

### CODE REVIEW

**Comment by nikita-b** [comment]
@IgnacioHeredia Could you, please, fix the linters?

**Comment by IgnacioHeredia** [comment]
@nikita-b done!

**Review by nikita-b — APPROVED** [review]

**Comment by nikita-b** [comment]
@IgnacioHeredia Oh, it seems we still have an issue with `black` formatter.

**Comment by IgnacioHeredia** [comment]
@nikita-b done!

**Pull request merged**
